name:                aoc2025-hs
version:             0.1.0.0
github:              "spaarmann/advent-of-code"
license:             MIT
author:              "Sebastian Paarmann"
maintainer:          "git@s-paarmann.de"
copyright:           "Sebastian Paarmann"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Advent of Code 2025!

dependencies:
- base >= 4.7 && < 5
- parsec >= 3 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-missing-signatures
- -Wno-incomplete-patterns

library:
  source-dirs: src

executables:
  aoc2025-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2025-hs

tests:
  aoc2025-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2025-hs
