[package]
name = "aoc2022"
version = "0.1.0"
authors = ["Sebastian Paarmann <git@s-paarmann.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
