#!/usr/bin/env fish

# Parse command line args
set argc (count $argv)
if test "$argc" != 1
	echo "Usage: add_day <day_number>"
	exit 1
else
	set day "$argv[1]"
end

set year (string split -f 2 -r -m1 / (pwd))

echo "Adding day $day to project for year $year..."

set main_path "app/Main.hs"
set day_path "src/Day$day.hs"

sed -i "/-- MARK:IMPORTS/i import Day$day" "$main_path"
sed -i "/-- MARK:DAYS/i\\    [\"day$day\", \"1\"] -> readFile \"input/day$day\" >>= print . Day$day.part1" "$main_path"
sed -i "/-- MARK:DAYS/i\\    [\"day$day\", \"1\", \"e\"] -> print \$ Day$day.part1 Day$day.example" "$main_path"
sed -i "/-- MARK:DAYS/i\\    [\"day$day\", \"2\"] -> readFile \"input/day$day\" >>= print . Day$day.part2" "$main_path"
sed -i "/-- MARK:DAYS/i\\    [\"day$day\", \"2\", \"e\"] -> print \$ Day$day.part2 Day$day.example" "$main_path"

cp ../tools/template_day.hs "$day_path"
sed -i "s/%DAY%/$day/g" "$day_path"
